### ISSUE TITLE
How to generate data to generate handwritten text of style of my prefrence

### ISSUE THREAD

**Issue by vis7** [swechhachoudhary/Handwriting-synthesis#9]
In this repository you are using "data.npy". How can I generate that from my handwritten text so that I can generate text in my Handwritting

**Comment by vis7** [comment]
I found the answer from demo video

**Comment by berinaniesh** [comment]
@vis7 You mean, [this](https://youtu.be/Ghsb3w0QACI) video?
I watched it and could not grasp how to generate `data.npy`. 
Can you explain a bit?

**Comment by vis7** [comment]
Sorry, It has more than three years since I did that, so I don't remember it now.


> @vis7 You mean, [this](https://youtu.be/Ghsb3w0QACI) video?
> I watched it and could not grasp how to generate `data.npy`. 
> Can you explain a bit?
